name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: configure & build
      uses: threeal/cmake-action@latest
      with:
        args: -DBUILD_EXAMPLES=OFF